server:
  port: 9999
management:
  endpoints:
    web:
      base-path: "/"
logging:
  level:
    root: INFO
mongoDb:
  mongoUsersDbName: "users"
  mongoUsersCollectionName: "users"
  uri: "mongodb://localhost:27017"